### ISSUE TITLE
외부 이미지가 삽입된 글의 경우 크롤링이 제대로 되지 않는 현상

### ISSUE THREAD

**Issue by KinKuro** [wokim/clien-archiver#2]
안녕하세요. 올려주신 프로그램으로 스크랩해둔 게시글을 잘 백업하게 되었습니다. 정말 감사합니다.

기능 사용 중에 발견한 오류가 있어 이슈 남깁니다.

원본 글에 외부이미지가 삽입된 경우에 크롤링이 안되는 현상이 있습니다.
추측으로는 이미지 저장 시 파일 주소를 기반으로 폴더를 생성하고 이미지를 다운로드 받는 것 같은데,
외부경로인 경우에는 주소를 폴더로 변환하는 과정에서 "https:" 라는 폴더를 만드려고 하는 문제인 것 같습니다.

윈도우 10을 사용하였고, clien-archiver-win-x64.exe 를 powershell에서 실행했으며
url연동, csv연동 모두 테스트 시 같은 현상이 발생했습니다.

아래에 커맨드창 이력 및 사용한 csv파일을 전달드립니다.

---

커맨드창 이력
```
Archiving URL: https://www.clien.net/service/board/lecture/15177864
크롤링 에러: ENOENT: no such file or directory, mkdir 'articles\팁과강좌\images\https:\cdn.clien.net\web\api\F01\9061939'
Archiving URL: https://www.clien.net/service/board/pds/16830113
크롤링 에러: ENOENT: no such file or directory, mkdir 'articles\자료실\images\https:\postfiles.pstatic.net\MjAyMTEyMjRfOTcg\MDAxNjQwMzMzMjI2Nzg0.o-ykoAaEgTyAHLFlMlDVDkcl69SnuGtlEtN3NSYdZRMg.55psaXrZT-xD94HF1VR1xybKCIQpDAjshDn11JR9qFwg.PNG.gogoyuijin'
```

csv파일 : [scrap.csv](https://github.com/wokim/clien-archiver/files/14806252/scrap.csv)

**Comment by wokim** [comment]
제보 감사합니다! 외부 이미지 생각을 못했네요 ㅜ.ㅜ..

**Comment by lowhillfoto** [comment]
안녕하세요. 좋은 툴을 만들어주셔서 정말 감사합니다.
다름이 아니라 url 을 하나하나 넣어서 하는건 매우 잘되는데 txt 파일로 저장해서 작동시키면 에러가 납니다. ㅠㅠ

![image](https://github.com/wokim/clien-archiver/assets/129965630/35202b8d-1fe8-4dec-bfa0-02e692abffa2)
<img width="575" alt="image" src="https://github.com/wokim/clien-archiver/assets/129965630/2d987877-708a-4957-abf2-742b62ac81dc">

참고로 윈도우 환경입니다.
맥에서 txt 파일을 저장했는데 혹시나 몰라서 csv 파일로 저장해서 작동해도 같은 에러를 내고 있습니다.

**Comment by wokim** [comment]
`clien-archive-win-x64-v0.0.3.exe archive --urls client_list.txt` 이렇게 해보시겠어요? 파일은 `--urls` 옵션으로 지정하셔야 합니다!
